.TH bsp 6 "14 February 1999"

.SH NAME
bsp \- node builder for WAD files

.SH SYNOPSIS
.B bsp
[
.B \-factor
.I n
]
[
.B \-picknode
{ traditional | visplane }
]
[
.B \-blockmap
{ old | comp }
]
[
.B \-q
]
[
.B \-noreject
]
.I input.wad
[
.B \-o
.I output.wad
]

.SH DESCRIPTION
.B BSP
builds the node and blockmap resources for levels in
a WAD file. Levels created with level editors 
won't run without these resources.
The program supports multilevel building, means it automatically
builds the resources for all levels found in the input WAD file.

.SH OPTIONS
.TP
\fB\-o\fR \fIout.wad\fR
Sets the name of the WAD file for output. Should not be the same as the input!
As with the input filename, it can be a - to indicate that standard input/output
should be used. Without this option, output is written to tmp.wad.
.TP
\fB\-factor\fR \fIn\fR
Changes the cost assigned to seg splits. Factor \fIn\fR can be any positive
integer, and the larger the factor, the more costly seg splits are.
A factor of 17 is the default and behaves just like earlier versions
of
.B BSP.
Most people do not need or want to change the default.
Changing the factor can sometimes prevent visplane overflows in WAD's;
but then again, some WAD's have just too many visplane overflows,
experiment with the \-factor option before giving up.
.TP
.B \-picknode { traditional | visplane }
In 
.B traditional
mode (the default), BSP aims to produce a balanced node tree that minimises the
number of lines that must be split in this process.
.B visplane
mode causes the node line picker to choose node lines in a way that is
empirically known to reduce or eliminate visplane overflows.
This is an old bug that affected the original Doom engine but does not affect
newer engines - if you don't know what this option is and have no problems
without it, you do not need it.
.TP
.B \-blockmap { old | comp }
This selects the algorithm used for generating the blockmap resource.
The
.B old
algorithm (currently the default, but this might change in future) produces 
a complete blockmap which contains some redundancy. The
.B comp
algorithm generates an equivalent blcokmap, but which eliminates this
redundancy, making a smaller resulting WAD file.
.TP
.B \-noreject
Normally, BSP creates a zero-ed reject map, which is sub-optimal but sufficient
for Doom to play the level. Other tools are available to build an optimal reject
map. If a level already has an optimised reject map, this option should be used
to stop BSP replacing it.
.TP
.B \-q
Does not show program banners or progress, for usage from other programs.

.SH SPECIAL EFFECTS
.LP
.B BSP
has some special effect features:
.LP
If a linedef has a sector tag >= 900, then it is treated as "precious"
and will not be split unless absolutely necessary. This is good to use
around borders of deep water, invisible stairs, etc.
.LP
Furthermore, just for a grin, if the lindef's tag is 999, then the
sidedef's x-offset set an angle adjustment in degrees to be
applied \- you can look straight at a wall, but it might come
right at you on both sides and "stretch".
.LP
.B Bsp
supports HOM-free transparent doors. Simply make the sector
referenced by the doortracks have a sector tag of >= 900. No need
to remember sector numbers and type them in on a command line \-\-
just use any sector tag >= 900 to permanently mark the sector
special.

.SH SUPPORTED GAMES
Doom, Ultimate Doom, Doom ][ and Final Doom.

.SH BUGS/LIMITATIONS
.LP
This program will built a good reject map, it will (unless told
otherwise) build a zero-ed one, where every sector is visible from any other
sector. For the final release of a level, a reject map should be built using a
suitable tool, such as RMB.

.SH AUTHORS
.LP
.B BSP
was written by Colin Reed and Lee Killough (killough@rsn.hp.com).
André Majorel did the Linux port, Udo Munk integrated the sources
into the WAD tool collection and minimal changes were made to compile
on other UNIX systems besides Linux. BSP is currently maintained by Colin Phipps
<cph@cph.demon.co.uk>.

