#!/bin/sh
#
# $Id: maintainer-build,v 1.1 2000/08/24 21:37:08 cph Exp $
# cphipps - short script to start building from a maintainer-clean'ed tree
#
aclocal && autoheader && automake --include-deps && autoconf
